task_name: tuning

search_method: optuna # grid | random | optuna
n_trials: 60
metric: f1_score
direction: maximize

param_space:
  n_estimators:
    type: int
    low: 50
    high: 500
    step: 50
  max_depth:
    type: int
    low: 3
    high: 12
  learning_rate:
    type: float
    low: 0.0001
    high: 0.01
  epochs:
    type: int
    low: 50
    high: 500
    step: 50
  min_samples_leaf:
    type: int
    low: 5
    high: 60
    step: 5
  l2_regularization:
    type: float
    low: 0.0
    high: 1.0
  batch_size:
    type: int
    low: 4
    high: 32
    step: 4
  num_layers:
    type: int
    low: 2
    high: 5
  layer_size:
    type: int
    low: 16
    high: 128
    step: 32
  dropout_rate:
    type: float
    low: 0.05
    high: 0.4
