task_name: load_ds

project: system_test
experiment: system_test
seed: 93

dataset_src: empty
dataset_path: E:\Uni\the_basics_of_intelligence\2\practice\HW4\ai_pipeline\data\Industrial_fault_detection.csv
target_name: Fault_Type
show: false # show plots
