task_name: dim_reduction

method: lda
n_components: 20

show: false

pca_svd_solver: auto

umap_n_neighbors: 15
umap_min_dist: 1.0
umap_metric: euclidean
umap_supervised: false

lda_solver: svd
lda_shrinkage: null